
const types = {
    GET_ERRORS:            'GET_ERRORS',
    GET_PLANETS:           'GET_PLANETS',
    PLANETS_LOADING:       'PLANETS_LOADING',
    VEHICLES_LOADING:      'VEHICLES_LOADING',
    GET_VEHICLES:          'GET_VEHICLES',
    SET_USER_SELECTION:    'SET_USER_SELECTION',
    MODIFY_USER_SELECTION: 'MODIFY_USER_SELECTION',
    RESET_USER_SELECTION:  'RESET'
}

export default types;